### PR TITLE
Project:- The-next-Web clone

### PR DESCRIPTION
**Pull request by hemantso**
##Project:- The-next-Web clone

- Navbar with position sticky having links and search icon and logo
- Multiple sections like News, Deals, Funding
- Each section with grid and flex style
- Footer with nav links and copyrights
- Site is responsive using two breakpoints

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this for some feedback in a few minutes :+1:

**Comment by nikasulo** [comment]
# Great work! @hemant-soni-vst-au4 and @ioilmio :medal_military: 
Your project is really great and well written. Your readme is very professional and most importantly, your project is super responsive. Please look into my comment below, make the necessary changes and request another review :ok_hand: 

#### Responsiveness
Please look into the last section of the project, just before the footer on tablet screen sizes. It doesn't present as is expected. Kindly make the necessary changes and request another review. I wish you the very best and see you at the top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by ioilmio** [comment]
just a one-line change can you check it again please

**Review by MarioDena — APPROVED** [review]
Hello! My name is Mario, well done on your project!!! 👍 

I see you made the requested changes, good job. However I would recommend some implementation to have your project be even better.

## Optional Changes

- [ ] Test your project for responsiveness on higher resolutions and adjust to fit really high resolution screens. This is [OPTIONAL].

Good job! 

## This project is approved all requested changes are optional

Feel free to make the recommended test or just merge and move on to the next project. 🏅 

## Code Review by Mario Enrique Delgado Naranjo

**Pull request merged**
